### PR TITLE
Added service tab

### PR DESCRIPTION
**Pull request by guglo**
This checkin includes:

    1. Added to display service template files in server group
    2. Added to allow user update individual service template file.

### CODE REVIEW

**Comment by guglo** [comment]
It depends on the backend change https://gerrit.suse.provo.cloud/#/c/1706/
Check https://suse-jira.dyndns.org/browse/SCRD-1434 for how to test.

**Comment by jeremy-moffitt** [comment]
Two things I would try to remedy if possible..
1. Its pretty easy to get double scrollbars on the right hand side. I clicked "neutron - lbaas-haproxy.filters.j2" and end up with the cancel/save buttons off screen. Those buttons should probably stay on screen while only the edit box scrolls. The double scrollbars even happen at fullscreen
2. when the edit dialog is open, it still looks like you can click the left hand side links.... but they don't do anything... I would obscure or hide the links... the simplest would be to put an opacity over the verticalLine section when the edit dialog is open. To match the functionality from the model screen, it would only show the edit dialog when editing is enabled

**Comment by guglo** [comment]
@jeremy-moffitt  1. will take a look. 2. There are some complains about the edit model screen...if you want me to go with that way...I am ok with that.

**Comment by jeremy-moffitt** [comment]
the right side still has a weird scrollbar, but it doesnt look like its new to this change

**Pull request merged**
