### PR TITLE
Added commit changes before run playbook

### PR DESCRIPTION
**Pull request by guglo**

### CODE REVIEW

**Comment by guglo** [comment]
The change need to have the backend change to work correctly : https://gerrit.suse.provo.cloud/#/c/1809/2

**Comment by jeremy-moffitt** [comment]
I wonder if it would make sense to add a step about committing the model to the deployment process... probably not mandatory (and would obviously need a different mechanism than the playbook callback to trigger)

**Comment by jeremy-moffitt** [comment]
One more note, not sure if its specific to this change or if it would happen on any failure, but when the commit fails the user cannot navigate back to a prior screen, they're basically stuck

**Comment by guglo** [comment]
@jeremy-moffitt  thanks for the review...will look into this.

**Comment by jeremy-moffitt** [comment]
looks better. Ideally we'd have a step in the process for "committing model" , i.e. something in the list of steps that the user sees progressing, but I think we have live with it as-is for now.

**Pull request merged**
